services:
  rpi_imagegen:
    build: .
    privileged: true
    stdin_open: true
    tty: true
    image: rpi-imagegen:latest
    volumes:
      - linko_data:/Linko-OS

volumes:
  linko_data:
    driver: local