services:
  rpi_imagegen:
    build: .
    privileged: true
    stdin_open: true
    tty: true
    image: rpi-imagegen:latest
    volumes:
      - ./Linko-OS:/Linko-OS
      - ${HOME}/Downloads:/host-downloads