#!/bin/sh

set -eu

# Write out our systemd service
rsync ../kiosk/first-boot.service $1/etc/systemd/system/first-boot.service

# trigger the systemd service to run on first boot
$BDEBSTRAP_HOOKS/enable-units "$1" first-boot

mkdir -p $1/opt/linko/launcher/
rsync ../linko/launcher/LinkoLauncher.jar $1/opt/linko/launcher/

chmod 755 $1/opt/linko/launcher/

APP="java -jar /opt/linko/launcher/LinkoLauncher.jar"

# Write out our systemd kiosk service
cat ../kiosk/kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<KIOSK_APP>|$APP|g" \
   > $1/etc/systemd/system/kiosk.service

# # Enable the kiosk service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

# Updater
rsync ../kiosk/kiosk-updater.service $1/etc/systemd/system/kiosk-updater.service

$BDEBSTRAP_HOOKS/enable-units "$1" kiosk-updater