#!/bin/bash

set -eu

pkgs=(dosfstools)

case $IGconf_image_rootfs_type in
   ext4)  pkgs+=(e2fsprogs) ;;
   btrfs) pkgs+=(btrfs-progs) ;;
esac

chroot $1 apt install -y "${pkgs[@]}"

usermod -a -G video,netdev player
chmod 755 /opt/linko/