#!/bin/sh

set -eu

mkdir -p $1/etc/wpa_supplicant
mkdir -p $1/etc/NetworkManager/system-connections/

chmod 755 $1/etc/NetworkManager/system-connections/

rsync ../kiosk/conf.d $1/etc/NetworkManager/