#!/bin/bash

set -eu

# configure the splashscreen
mkdir -p $1/usr/share/plymouth/themes/linko
chmod 755 $1/usr/share/plymouth/themes/linko

rsync -a ${IGIMAGE}/plymouth/themes/linko $1/usr/share/plymouth/themes/

chmod 644 $1/usr/share/plymouth/themes/linko/*

# set the default theme to linko
#chroot $1 plymouth-set-default-theme linko

# Old cmdline.txt which used plymouth
#console=serial0,115200 root=ROOTDEV rootfstype=ext4 fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles logo.nologo loglevel=0 rd.udev.log_priority=3 vt.global_cursor_default=0 consoleblank=0