#!/bin/sh

set -eu

mkdir -p $1/opt/linko/launcher/
rsync ../linko/launcher/LinkoLauncher.jar $1/opt/linko/launcher/

chmod 755 $1/opt/linko/launcher/

# Write out our systemd service to unblock wifi
rsync ../kiosk/unblock-wifi.service $1/etc/systemd/system/unblock-wifi.service

mkdir -p $1/etc/wpa_supplicant

APP="java -jar /opt/linko/launcher/LinkoLauncher.jar"

# Write out our systemd kiosk service
cat ../kiosk/kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<KIOSK_APP>|$APP|g" \
   > $1/etc/systemd/system/kiosk.service

# # Enable the kiosk service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

# Permissions to use GPU?
usermod -aG video $IGconf_device_user1